### ISSUE TITLE
Feature request-: Make it a extension in text generation webui 

### ISSUE THREAD

**Issue by TruthSearchers** [chrisrude/oobabot#11]
A feature request ,it will be cool if you make this as extension of ooobaboga (text generationwebui) so we can run it simultaneously with text generation web ui

That will be cool 
There is telegram bot like this as extension

**Comment by chrisrude** [comment]
It's getting close!
![bot-ui](https://github.com/chrisrude/oobabot/assets/12817326/0f42584b-3778-4e95-b1f3-e6eae11862ad)

**Comment by chrisrude** [comment]
Still needs some more tweaking, particularly integration with some of the conversational model settings now that I can read them more easily.

Then to see if I can get it landed as a default plugin!

**Comment by TruthSearchers** [comment]
Ohh damn , thanks men

**Comment by chrisrude** [comment]
Ok, I need some help testing.  Anyone interested?

To do so:
- go to your oobabooga install directory, (text-generation-webui)
- activate your conda environment if necessary
- run:
```bash
pip install oobabot-plugin
```
a bunch of stuff should be installed
- then run:
```bash
oobabot-plugin install
```
You should see something like:
```
oobabot installed!
Please restart the server and enable the oobabot plugin.
```
Then, do that!  You should see a new "oobabot" plugin under the "interface mode" tab.

Enable it, along with the API plugin if you haven't already.  Now you should have a new "oobabot" tab on the top that looks like this:
![image](https://github.com/chrisrude/oobabot/assets/12817326/b7fcf6a2-5792-44cd-bc92-b6bfac42c717)

Have fun, and please post here what worked and what didn't.  I would love it if some of you wonderful folks could help let me know if / how it works before spreading the word more broadly.

**Comment by TruthSearchers** [comment]
I will try it out

**Comment by TruthSearchers** [comment]
Hey there bro i just tried it out 
First of all it's amazing works perfectly 
There is some issues i faced and noticed 
i) Ui ( upper part of ui (section in which start oobabot and stop oobabot and some lines are hiding behind) (these buttons only half visible)(it's possible that it's issue only from my side because i am using different theme)
ii) when i close (uncheck) oobabot in interface mode , it don't close instead , don't able reload ui again

---Add more options such as max_tokens  and other params (or take as it is from parameters tab in web ui) 
Some more stable diffusion options such as negative prompt , sampler , steps etc


Also a suggestion if possible (text streaming is not smooth ) (like it stop sometimes in middle etc)

**Comment by chrisrude** [comment]
Awesome, thanks for trying it out!

> i) Ui ( upper part of ui (section in which start oobabot and stop oobabot and some lines are hiding behind) (these buttons only half visible)(it's possible that it's issue only from my side because i am using different theme)
It would be helpful if I see the problem in a bit more detail.  Would you mind sending a screenshot of the problem?

> ii) when i close (uncheck) oobabot in interface mode , it don't close instead , don't able reload ui again
yeah, I looked into this a bit already and it's a gradio issue.  I might try and see if I can work around it on my side, or land a fix there.  But it's something I want to fix before pushing this out more broadly.

> Also a suggestion if possible (text streaming is not smooth ) (like it stop streaming sometimes in middle etc)
Yeah, I think I might hide it from the UI for now.

**Comment by chrisrude** [comment]
Calling this done as 0.1.9 of https://github.com/chrisrude/oobabot-plugin is out!  Please file any requests for that package in that respository.
