### ISSUE TITLE
random token responses when running vicuna-AlekseyKorshuk-7B-GPTQ-4bit-128g

### ISSUE THREAD

**Issue by FellowChello** [chrisrude/oobabot#12]
Hey, it was a bit of a pain to get even to this point but now I am at a full stop: 
oobabot: error: Please set the 'DISCORD_TOKEN' environment variable to your bot's discord token.

This dreaded message is what i get every time. Even after setting the variable and even creating a environment file and changing DISCORD_TOKEN in every possible file I could fins. 

Would appreciate some insight how to get past this. 
Re-download everything?

**Comment by chrisrude** [comment]
Sorry to hear it's been frustrating!  It's hard to know exactly what isn't working, but I don't think you need to re-download anything.

The first thing I would try is to make sure the environment variable is set to "export" in your shell of choice (typically, Bash)

You can see if this is the problem by running this command in the same place you were trying to run `oobabot`:

``` bash
  export -p | grep DISCORD_TOKEN
```

If that doesn't report anything then you've found the problem.  If that's the case, this guide might have some useful information:
  https://www.baeldung.com/linux/bash-variables-export

Let me know if this helps resolve the problem or not.  Good luck!

**Comment by FellowChello** [comment]
thank you for the hint, I ended up wiping out the install folder and re-downloading everything. Set the variable and it looks like it started. But some weird behavior: 
reply to Hey was this:

Paladin
BOT
 — Today at 4:40 PM
or around when the us or down and the same or the v ul se ** or the gu i or the p or a or a or a and a pro or a or a and a a or a or a and a under a or a and a and a a or a and a or a or a and a or a or a and a or a or a and a or a and a or a and a or a and a or and a or and a and a or a and a or a and a or a and a or a and a or a and a or a and a or a and a or a and a or a and a or a and a or a and a or a and a and a or a and a or a and a and a and a or a and a and a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or

Any idea what is going on?

**Comment by chrisrude** [comment]
Glad that worked!

My guess would be that the text is what is generated on the oobabooga side.  One way to confirm is:

- Run oobabot with the `--log-all-the-things` command-line argument

This should print out the prompt that is being sent to the server, as well as it's reply.

I'd then copy the prompt into the Oobabooga web UI, completely replacing the default input there, and see if you get the same thing generated or not.

If it is different, please let me know!  If it's the same, oobabooga's folks might be better able to help you troubleshoot.

**Comment by FellowChello** [comment]
trying to check the output but it looks like no matter what the message is the reply is the same'ish. 

I pasted in the transcript in WebUI and that gave an actual answer / follow-up. 
Any idea where the mixup could be?

**Comment by chrisrude** [comment]
Interesting.  Could you please paste here what gets logged when you enter a message while `--log-all-the-things` is set?

The text I'm interested in should start with
```
prompt_prefix:
```
and end with
```
Response:
----------
````

Thanks!

**Comment by FellowChello** [comment]
thank you for working on this with me, here is the log: 

prompt_prefix:
----------


You are in a chat room with multiple participants.
Below is a transcript of recent messages in the conversation.
Write the next one to three messages that you would send in this
conversation, from the point of view of the participant named
"Paladin".
I am a young woman who has recently come into her powers as a Paladin. I have been tasked with protecting the innocent and upholding justice, but I still have much to learn about my abilities and how to best use them. I am determined to do everything in my power to fulfill this duty and become the greatest Paladin that ever lived.

All responses you write must be from the point of view of
Paladin.
### Transcript:
DislikedWolf50 says:
Ohh man 😅

HelloI'mFellow says:
lool like what happened 😄

HelloI'mFellow says:
it's borked

HelloI'mFellow says:
I guess it is time to work on another one

HelloI'mFellow says:
going to wipe out the settings and see if anything I did changed stuff 😄

HelloI'mFellow says:
if not ill try another method

Ping Ping says:
<a:ThisIsFine:937433520601706567>

HelloI'mFellow says:
ohh yeah it is on fire lol

HelloI'mFellow says:
but this one actually monitors the chat \

HelloI'mFellow says:
<@1104612154918842459>  hey, how are you?

Paladin says:

Response:
----------

or even around and the gu - or rather se or us for a certain and the same and a or down and a or a under and or a or a and a or around and a or a and a or a and a or a and a and a and a and a and a and a or a and a when a and a or a and a and a or a and a or a and a and a or a and a or a and a or a and a and a or a and a and a or a and a and a or a and a and a or a and a and a or a and a and a and a or a and a and a or a or a or a and a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or a or
←[33m2023-05-10 17:32:50,352←[0m DEBUG ←[36mResponse to HelloI'mFellow done!  tokens: 249, time: 17.23s, latency: 17.23s, rate: 14.45 tok/s←[0m

**Comment by FellowChello** [comment]
another thing i noticed is that every response is 249 tokens

**Comment by chrisrude** [comment]
super interesting.  Could you please paste the output it produces when you paste the prompt into oobabooga directly?

**Comment by FellowChello** [comment]
here is the response: 

Assistant
Paladin says:

Hi there! How can I assist you today?

**Comment by FellowChello** [comment]
ohh super strange, I just copied another output and was able to reproduce the nonsense. 

and now it just responds in a nonsense every time I paste the prompt. That is very strange.

**Comment by FellowChello** [comment]
It looks like there is something weird going on with the last 2 - 4 lines of the message being sent

**Comment by chrisrude** [comment]
Interesting.  Could you link to the model you're running on oobabooga?

**Comment by chrisrude** [comment]
I'm planning to add more user control over what actually gets sent over, so that you should be able to customize it a bit to make your model happy.  But it would be even better if I can try to get the defaults working well with more models out of the box.

**Comment by FellowChello** [comment]
this is the model: vicuna-AlekseyKorshuk-7B-GPTQ-4bit-128g

I really like the way how your bot is monitoring the Discord. I am using another bot right now that uses the / reply command and that seems to work well. And I can add the character context in variables that are passed. 

Is there a way to take out the persona part and pass it to API as "context" ?

**Comment by chrisrude** [comment]
Interesting.  Specifically it sounds like you enjoy being able to configure the bot via /commands, rather than a server config.  Is that correct?

I haven't fixed anything directly related to this issue, but v0.1.5(just released) has a new parameter called`--history-lines` which lets you set how much history you can send to the bot.  I've noticed that on my setup when that's too high, I get somewhat gibberish response.  I don't think it's super likely to fix your issue, but lowering it might help.

Longer-term, I've made some changes under the hood which will let you completely customize the prompt that gets sent to Oobabooga.  So that way we don't have to find as single prompt that will work for all models, and it will give a whole lot more knobs for fixing these sorts of issues.  Stay tuned!

**Comment by FellowChello** [comment]
Awesome, i will give that a try today or tomorrow. 
I mainly like to predefine the settings on the bot or server script. that way if thing's need to be restarted I can do so without worrying of losing any presets and I can test thing's reliably. 

I was wondering if the issue is with how the prompt is fed into latest update of the webui and  the prompt trying to say persona VS passing the characteristics as context. 

Thank you for working on this, I would really love to use your bot due to the natural way of interactions

**Comment by chrisrude** [comment]
updated title to reflect current nature of bug

**Comment by FellowChello** [comment]
Great news, I tried 2 other models and was able to make it work. However there seems to be some issue with Bot starting to reply to every message even when no wake word or mentions is present

**Comment by chrisrude** [comment]
Thanks for following up, glad it worked for you!
