### ISSUE TITLE
bot responds to channels even without / permissions

### ISSUE THREAD

**Issue by chrisrude** [chrisrude/oobabot#13]
the bot seems to monitor all channels, even ones in which it doesn't have / permissions.  Whoops!  Fix it.

Thanks @S1gil0 for pointing this out!

**Comment by chrisrude** [comment]
Actually, this does work, I just pointed you at the wrong part of the Discord UI.

Could you please try this instead and let me know if it works for you?

In your server, right-click on the channel you want to remove access to, then choose "Edit Channel", then "Permissions"

Assuming this is a public channel, you'll need to click "Advanced Permissions".  You should get something which kinda looks like this:
![image](https://github.com/chrisrude/oobabot/assets/12817326/115ac633-1252-4c18-9c0f-d0b64d3a0dbe)

Here, *RosieAI* is the name of my oobabot.  You'll see the name of your own bot, and later on, the name of the bot account (with the #0000 identifier).

Select each of these in turn, and change "View Channel" to "X".

Hit "Save Changes".

The bot should no longer operate in that channel.

Please let me know if this works for you!

**Comment by S1gil0** [comment]
it is working, ty (=

**Comment by chrisrude** [comment]
Awesome, glad to hear!  Apologies for steering you wrong, and the next update will have this in a FAQ so that others can benefit from the knowledge in the future. :)
