### ISSUE TITLE
Feature request : Can you do something so it can generate full text, not always splitting

### ISSUE THREAD

**Issue by TruthSearchers** [chrisrude/oobabot#15]
First of all i tried bot and it's amazing really loved it 

Some improvement if i can suggest like let's suppose someone want an article or code 
But the problem coming is that it split the code making in multiple lines 

If you can do something it can generate long replies and code 
Plus also split when needed

**Comment by TruthSearchers** [comment]
If text streaming can be done on discord , it will be so cool

**Comment by chrisrude** [comment]
I've added a `--dont-split-responses` option which will bundle the entire response into a single message.

This doesn't address the "only split when needed" request, though, but should address @Skrownerve's concern.

The fix should be included in v0.1.6, which I expect to have show up next week.

**Comment by chrisrude** [comment]
Closing issue even though I don't have it sometimes-splitting, because I honestly don't know how I'd detect when to split and when not to.  If anyone has any ideas on a reliable heuristic for that, please feel free to drop a comment.
