### ISSUE TITLE
Issue facing while clicking on Try again button on image

### ISSUE THREAD

**Issue by TruthSearchers** [chrisrude/oobabot#16]
Hey there I was facing a issue when click on Try again as it not try again also no error in console too so don't able to understand 

Also can you add --stable-diffusion-prefix-prompt too it will be very helpful 

Thanks men

**Comment by chrisrude** [comment]
@TruthSearchers I've added more logging for the "Try Again" button in the 0.1.5 update, which is just out.  It won't fix your issue, but should give us more information about what's going on.

If you see this again, could you please update this task with the error you're getting?  Thanks!

**Comment by chrisrude** [comment]
v0.1.6 is out, which I think might fix this.  Please reopen if it still happens on that version

**Comment by TruthSearchers** [comment]
Hey bro issue is still in logs this error coming 

Error : Could not regenerate image : 404 not found (error code : 10062) : unknown interaction

Everything else working fine (no problem). In latest version

**Comment by chrisrude** [comment]
@TruthSearchers if you can try building from source, I'm 99.9% sure I've fixed this finally. :). Let me know!

**Comment by TruthSearchers** [comment]
I will try with branch thanks bro
