### ISSUE TITLE
feature preview: text streaming

### ISSUE THREAD

**Issue by chrisrude** [chrisrude/oobabot#24]
For those of you building the source yourself, check out [this commit](https://github.com/chrisrude/oobabot/commit/823b52adf22a65e7127387a6d77a64acc83e68d4).  It's a preview of streaming responses to Discord.

You can run it with the `--stream-responses` argument.

The feature is still a little janky, so I'm looking for feedback about how it works for folks before including it in an official release.

**Comment by chrisrude** [comment]
FYI to @TruthSearchers

**Comment by TruthSearchers** [comment]
Thats cool men thanks for it

**Comment by chrisrude** [comment]
v.0.1.7 is out, have fun with it!

**Comment by TruthSearchers** [comment]
Yeah i tried  , text streaming is not smooth , it like sometimes stop in middle and suddenly whole para , i forgot to tell you when i tried branch one

Also at every discord message end (editing ) is getting written 

These some improvements needed in text streaming 

Thanks men in advance You are amazing
