### ISSUE TITLE
Feature request: option/command to restrict unsolicited responses to a single channel or thread per server

### ISSUE THREAD

**Issue by rebek43** [chrisrude/oobabot#33]
What the title says. This could serve as a way to reduce clutter caused by the bot in large servers.

**Comment by rebek43** [comment]
> But it sounds like you're asking for something different, which is for the bot to respond to direct pings but to not follow up with unsolicited responses in all but one channel. Is that right?

Correct

**Comment by chrisrude** [comment]
Been thinking about this; what if the restriction were around the number of channels the bot could participate in.  i.e. it would post unsolicited messages only in the two most recent channels it was summoned in.

**Comment by chrisrude** [comment]
I'm trying as much as possible to have a sensible set of default behaviors.  When there are tons of options that can be intimidating to folks and ask a lot of their time, and I want to make this as easy as possible for folks to just get something working.

Limiting it two 2 unsolicited channels also furthers the goal of having the bot act as "human-like" as possible... a human wouldn't carry on a conversation in more than a few channels at a time.  And it would serve the requested goal of limiting spam in large servers.

That said, if the bot keeps getting pinged back and forth in different channels it could still create a lot of noise, but the solution to that might be for the admin to restrict the channels it has access to.

**Comment by chrisrude** [comment]
@rebek43 I added this in the above commit:

Adds a new `unsolicited_channel_cap` option in
`discord` section of `config.yml`.  It does this:

> FEATURE PREVIEW: Adds a limit to the number of channels
> the bot will post unsolicited messages in at the same
> time.  This is to prevent the bot from being too noisy
> in large servers.
> 
> When set, only the most recent N channels the bot has
> been summoned in will have a chance of receiving an
> unsolicited message.  The bot will still respond to
> @-mentions and wake words in any channel it can access.
> 
> Set to 0 to disable this feature.

Assuming you have a `config.yml` file already, you can generate an updated version with `cp config.yml config.yml.backup && oobabot -c config.yml.backup --gen > config.yml`

You can then `diff config.yml.backup config.yml` to see what changed.

If you are running from source, do you want to try this out and let me know how it works for you?  If not it should be in the next release.

**Comment by rebek43** [comment]
should do the trick
thanks
