### ISSUE TITLE
Feature Suggestion: Specify Stable Diffusion model in prompt/message

### ISSUE THREAD

**Issue by jmoney7823956789378** [chrisrude/oobabot#37]
I keep multiple models stored in VRAM for stable diffusion, and I would like to specify the model to be used when asking the bot to draw something.
For example:
model1=StableDiffusion1.5.safetensors
model2=WaifuDiffusion1.4.cpkt
(both loaded in vram or ram)
botname, (use model1 to) draw a tuna sandwich
will use the SD1.5 model for the prompt.
botname, (use model2 to) draw hatsune miku
will use the WD1.4 model for the prompt.

**Comment by chrisrude** [comment]
Cool, I didn't know you could keep multiple models in ram at once!  The reason I hadn't added it before is the presumed delay in switching models.

**Comment by johnmoney83748932** [comment]
You can opt to keep last # models in RAM.

**Comment by johnmoney83748932** [comment]
Semi related:
When trying to specify SD sampler "DPM++ SDE Karras", it seems to default back to euler.

**Comment by johnmoney83748932** [comment]
Could you consider adding a command to query the SD server for available loras?
I've been reading the docs and it looks like there is a lot of potential for customization.
`1.2.3.4:7860/sdapi/v1/loras`
should return a huge json formatted list, including lora names, location, meta, etc.
I think we should only need the name and/or alias, to be used in a SD request prompt.
You can also request available models at: `/sdapi/v1/sd-models` but I'm still not sure if you can switch to a new model via api.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/8041
This thread seems to have a method implemented, but as for how you'd tell the bot which model to use, I'm thinking maybe  something like a slash command. Same method could be valid for asking the bot to query loras.

**Comment by chrisrude** [comment]
I made a small change for this: https://github.com/chrisrude/oobabot/commit/bc2f11c548717304b18bcadffd88148251e7f0e2

If a message request contains the name of a Stable Diffusion checkpoint, we will use that checkpoint to generate that specific image, then change back to the default afterwards.

We'll log the valid names at startup, to make it easier.

e.g.
> Hi Rosie, make me a picture with Anything-V3.0 of a cat

Let me know what you think!

**Comment by johnmoney83748932** [comment]
Awesome. Really amazing stuff you're putting together!
Any potential for a `/models` or `/loras` to show available options in chat?

**Comment by chrisrude** [comment]
Interesting; what do the logs say during startup and when the image generation is attempted?  It should print out a message at each of those times related to models.

**Comment by johnmoney83748932** [comment]
Here's startup, followed by my invoked command:

```
2023-06-08 00:09:34,765  INFO Starting oobabot, core version 0.1.10
2023-06-08 00:09:34,765  INFO Oobabooga is at ws://10.20.230.242:5005/
2023-06-08 00:09:34,773  INFO Connected to Oobabooga!
2023-06-08 00:09:34,773  INFO Stable Diffusion is at ws://10.20.230.240:7860
2023-06-08 00:09:34,789 DEBUG Stable Diffusion: Using desired sampler 'DPM++ SDE Karras'
2023-06-08 00:09:34,802 DEBUG Stable Diffusion: Options are already set correctly, no changes made.
2023-06-08 00:09:34,812  INFO Stable Diffusion: Available models: anything-v4.0-pruned-fp16, detailedprojectv4-fin, eden_V16, HoloAOM_3A1B, HoloKukiv2.2EyeFix-fp16, level4_v40BakedVAEFp16, level4_v50BakedVAEFp16, pastelMixStylizedAnime_pastelMixPrunedFP16, v2-1_768-ema-pruned, minaimix_, 512-base-ema
2023-06-08 00:09:34,812 DEBUG Stable Diffusion: Using negative prompt: easynegative, ng_dee...
2023-06-08 00:09:34,812  INFO Connected to Stable Diffusion!
2023-06-08 00:09:34,813  INFO Connecting to Discord... 
```
Here is a screenshot of output. For reference, I currently have the SD model "minaimix_" loaded. Draw word is "draw".

![1686183326_Discord_6XDdiauuKt](https://github.com/chrisrude/oobabot/assets/133553475/beaac461-e337-417e-87dd-d960429fa4a5)

This output is found in the logs, and is identical all three times I invoked the draw word.

```
2023-06-08 00:11:16,065 DEBUG Found image prompt: obama
2023-06-08 00:11:16,065 DEBUG Request from stoop poops in -DM-
2023-06-08 00:11:16,066 DEBUG Stable Diffusion: Image request (nsfw: False): obama
```

**Comment by chrisrude** [comment]
Will take a look in the next few days, I likely made some error.  Thanks for the detailed report!

**Comment by johnmoney83748932** [comment]
Looks like I got it to work, but you have to include the model in the actual SD prompt.
Mentioning in any of the models before the SD invoke word is just ignored.
![1686273168_Discord_29trdfVsKl](https://github.com/chrisrude/oobabot/assets/133553475/cf75bc2c-91c3-43f1-bc34-73b0b3666cb4)

**Comment by chrisrude** [comment]
So I was inspired by your earlier PR, and also anticipating users adding a bunch of requests saying "well I also want to be able to set xxx=yyyy can you add that please".  333b4b8fd73f0e91b84594b2b48e2938e651e974

So, I expanded `settings.yml` to allow for a new parameter, `user_override_params`.  This is what it sounds like -- any param name listed can be overridden, by setting param=value in the message.

It's required that all param names also appear in `request_params`, as we use that to determine the parameter's type for validation purposes.

Since this means we might now have multiple multi-word values, I changed the behavior of `np=` to instead take a quoted string.  In fact a quoted string will now work for any value, so you can say something like:
   `np="cats, dogs, helicopters" sampler="DPM++ SDE Karras", steps=20`

And it would work as you'd expect.  Leaving out the quotes wouldn't work, as it would just take the text up until the first whitespace.

I also cleaned up the half-assed code I wrote to set model checkpoints above, and incorporated it in to work as just described.

Let me know what you think!

**Comment by jmoney7823956789378** [comment]
> So I was inspired by your earlier PR, and also anticipating users adding a bunch of requests saying "well I also want to be able to set xxx=yyyy can you add that please". [333b4b8](https://github.com/chrisrude/oobabot/commit/333b4b8fd73f0e91b84594b2b48e2938e651e974)
> 
> So, I expanded `settings.yml` to allow for a new parameter, `user_override_params`. This is what it sounds like -- any param name listed can be overridden, by setting param=value in the message.
> 
> It's required that all param names also appear in `request_params`, as we use that to determine the parameter's type for validation purposes.
> 
> Since this means we might now have multiple multi-word values, I changed the behavior of `np=` to instead take a quoted string. In fact a quoted string will now work for any value, so you can say something like: `np="cats, dogs, helicopters" sampler="DPM++ SDE Karras", steps=20`
> 
> And it would work as you'd expect. Leaving out the quotes wouldn't work, as it would just take the text up until the first whitespace.
> 
> I also cleaned up the half-assed code I wrote to set model checkpoints above, and incorporated it in to work as just described.
> 
> Let me know what you think!

It's working great! 
I saw you pretty much redid the whole params part to be pretty open-ended, which is awesome. 
Thank you for all that you do!
