### ISSUE TITLE
Can't use config.yml file

### ISSUE THREAD

**Issue by TruthSearchers** [chrisrude/oobabot#41]
Hey man ,how are you 
I am trying to use config.yml but due to some reason it's not working 
I tried but it not reading that config.yml file 
It generated without any problem from --generate-config>config.yml
But when i use --c or --config-file according to you config.md doc it's not working at all
As i can say because it's loading on base_url default link 
And i already putted all details of base_url etc

**Comment by johnmoney83748932** [comment]
Syntax is just
`oobabot -c config.yml`
Post error log

**Comment by TruthSearchers** [comment]
Actually it's also not working 
It trying to connect to default localhost:5005 but i already provided it with base_url in config.yml 
In error it's just showing 
Info oobaboga is at ws://localhost:5005
Error : couldn't find oobabbooga in 5005 
Please check url 

It's working fine when i  direct use command --base_url wss://customelink
But if i put it in config.yml it's not working at all

**Comment by chrisrude** [comment]
Interesting.  My first guess would be that the current directory when running Oobabot might be in a different place than you expect it to be.

Are you running on OSX, Linux, or a different platform?

The bot won't currently print out a message when it can't open a config file, so it can be hard to figure out what isn't working.  One idea I had, just for debugging, would be to run it like this:
   `oobabot --bogus (readlink -f config.yml)`
On OSX and Linux, that should then print out an error message with the full path to what would have been opened, e.g.::
   'oobabot: error: unrecognized arguments: --bogus /home/oobabot/config.yml'
Then double check if the file is in that location.

Let me know if this helps!

**Comment by chrisrude** [comment]
adding a milestone to add a warning message to make this easier to debug in the future

**Comment by chrisrude** [comment]
Added a more helpful error message in https://github.com/chrisrude/oobabot/commit/95cc19484b97063311ff77fe43d097ef554da646

Hopefully this will help in troubleshooting such problems.
