### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by Urammar** [chrisrude/oobabot#46]
Hi, I cannot for the life of me work out how to actually use this.

I've followed all the steps and now have the bot in the server and the pip install done

However... how do I launch the actual application? How do I give the bot its token? How do I point it to my local ip? I think the install guide is missing a few steps...

**Comment by Urammar** [comment]
![image](https://github.com/chrisrude/oobabot/assets/40313782/918ef7b5-6670-49c8-902c-67c710fb3a99)

**Comment by jmoney7823956789378** [comment]
The installation works very well on Linux systems. I saw you were trying to export a variable on windows, try using `set` instead.
Launching on windows should be the same as Linux, try `oobabot <args>`
or try python -m oobabot

**Comment by Urammar** [comment]
Thanks that worked! Okay so last step we have everything ready to go

Now this

```
C:\MyShit\AI\Flan-t5-XXL\OobaBot>python -m oobabot --base-url ws://localhost:7860/ --ai-name YourBotsName --persona "You are a cat named YourBotsName"
←[33;40m2023-06-22 03:59:48,265←[0m←[37;40m  INFO ←[0m←[37;40mOobabooga is at ws://localhost:7860/←[0m
←[33;40m2023-06-22 03:59:50,322←[0m←[37;40m ERROR ←[0m←[31;40mCould not connect to Oobabooga server: [ws://localhost:7860/]←[0m
←[33;40m2023-06-22 03:59:50,323←[0m←[37;40m ERROR ←[0m←[31;40mPlease check the URL and try again.←[0m
←[33;40m2023-06-22 03:59:50,323←[0m←[37;40m ERROR ←[0m←[31;40mReason: 403, message='Invalid response status', url=URL('ws://localhost:7860/api/v1/stream')←[0m
```

**Comment by Urammar** [comment]
API is checked in the boolean command-line flags in the UI and I hit apply and restart the interface.

![image](https://github.com/chrisrude/oobabot/assets/40313782/a462c033-50f9-488a-997d-d244f0920100)

The final code on the command prompt says its running, but doesnt mention the API, unsure if its supposed to

**Comment by Urammar** [comment]
Yup that fixed it, thanks a ton for your help! I'll let you know how it goes!

**Comment by Urammar** [comment]
Its very slow compared to ordinary generation, i'll open a 2nd issue for that

**Comment by Urammar** [comment]
Its very slow compared to ordinary generation, i'll open a 2nd issue for that
