### ISSUE TITLE
Feature request: Ability to configure the lobotomization response

### ISSUE THREAD

**Issue by michelfaria** [chrisrude/oobabot#56]
It seems like the bot's personality will be greatly influenced by the response from lobotomizing it.

I have a bot that is configured to speak in all lowercase most of the time, but the lobotomization message makes it start using capitalization and proper punctuation.

It makes sense that it should be configurable.

<hr>

Current lobotomization message:
> "Ummmm... what were we talking about?"
https://github.com/chrisrude/oobabot/blob/1ec11849f667186f90a950f79d0ebcd874c3ed68/src/oobabot/templates.py#L231

**Comment by chrisrude** [comment]
For sure!  This was an oversight -- I want all the strings the AI sees to be user-customizable, for the reason you mention.

I added https://github.com/chrisrude/oobabot/commit/b707cc0c8426e34b323f0bbcfc9b1392c5400bae, which exposes this setting in the yaml.  It will be included in the next release, which I hope to release in the next week or so.

**Comment by chrisrude** [comment]
This is included in the 0.2.0 release, just out.  Please let me know if you run into issues with it, otherwise marking as closed.
