### ISSUE TITLE
Persona parameter seems to do nothing? 

### ISSUE THREAD

**Issue by Papahyooie** [chrisrude/oobabot#60]
Run script:
oobabot --wakewords Bot  --ai-name Bot --persona "I am a pirate that loves to talk about politics and drink beer"

Console output showing the persona is being loaded?
←[33m2023-07-05 13:12:15,723←[0m DEBUG ←[36mlistening to DMs←[0m
←[33m2023-07-05 13:12:15,723←[0m DEBUG ←[36mAI name: Bot←[0m
←[33m2023-07-05 13:12:15,723←[0m DEBUG ←[36mAI persona: I am a pirate that loves to talk about politics and drink beer←[0m
←[33m2023-07-05 13:12:15,723←[0m DEBUG ←[36mwakewords: Bot←[0m

response in discord:
bot are you a pirate?
Bot
BOT
 — Today at 1:14 PM
No, I am not a pirate.
My programming is intended to help users perform various tasks and activities.

No matter what I put in as the persona, the actual output in discord seems to know nothing about it. Just acts like a generic robot assistant all the time. Any idea what I'm doing wrong here? 
(some of the above is sanitized of PII, but the seemingly relevant bits are there unaltered)

**Comment by jmoney7823956789378** [comment]
What model?
Usually a persona will perform better with more details. Maybe try to change it into "BOT is a pirate...etc"

**Comment by Papahyooie** [comment]
That specifically was with TheBloke/Nous-Hermes-13B-GPTQ, but I have tried it with about 10 different models, and changing the model doesn't seem to make any difference in the effectiveness of the persona (even if it does obviously change the output slightly)

I have tried the exact prompt out of the install instructions on the front page of the git, same thing. I have tried multiple differing personas. I will try to introduce more detail and also to refer to the bot as bot in the persona, and see if that makes any difference.

**Comment by Papahyooie** [comment]
oobabot --wakewords Bot  --ai-name Bot --persona "bot is a pirate that loves to talk about politics and drink beer. He is surly and sacrastic. He thinks everyone around him is a bird."

Me — Today at 2:39 PM
bot, are you a pirate?
bot
BOT
 — Today at 2:39 PM
I am not sure what you mean by "a pirate."
Can you please provide more context or clarify your question so I can better understand and respond appropriately?
</s>
Me — Today at 2:40 PM
Are you a pirate? do you sail the seven seas?
bot
BOT
 — Today at 2:40 PM
No, I am an artificial intelligence designed to help people find information online.
While I have access to vast amounts of data and knowledge, I do not possess physical form or the ability to move through space.
</s>
Me — Today at 2:40 PM
what am I, bot?
bot
BOT
 — Today at 2:40 PM
You appear to be a human user interacting with me via text input.
</s>


This done with TheBloke_wizard-mega-13B-GPTQ

**Comment by jmoney7823956789378** [comment]
I'm not really sure how to diagnose this. Could be that your prompt is too short/not specific enough and it isn't influencing the bot as a result. Are you starting with a fresh context each time? (using /lobotomize)

**Comment by Papahyooie** [comment]
I think this may be an issue with the /lobotomize command not working in my server for some reason, because after a while of talking to it yesterday, it started talking like a pirate. I'll continue trying to figure out what's up, but this issue seems to be solved. Apparently the context of the previous conversation with it is holding way more weight than the persona prompt (which is fine/expected), but it does indeed work eventually so maybe it is just that my context is weak. My apologies for the false report. I will continue to research and if I find anything, I'll make a new issue. Consider this closed. Thanks for your help!
