### ISSUE TITLE
new feature: Stable Diffusion image generation

### ISSUE THREAD

**Issue by chrisrude** [chrisrude/oobabot#7]
@Skrownerve

> Sending/receiving images: Oobabooga has extensions for [generating images with SD](https://github.com/oobabooga/text-generation-webui/tree/main/extensions/sd_api_pictures), as well as [recognizing images](https://github.com/oobabooga/text-generation-webui/tree/main/extensions/send_pictures). I would love for our bots to be able to do these things. Even if not able to generate images, being able to search for/send images/GIFS would also be neat. I just don't know how it is done.

I've actually been working on this for a while!  The first version of the feature is now committed, and should be included in the next release.  I think it's pretty cool.

![image](https://github.com/chrisrude/oobabot/assets/12817326/009105e2-639b-4dd8-9fb6-eab15d433080)

It even has a fancy UI to let the user regenerate the image until they're happy with it, since SD can be hit-or-miss sometimes.  And it's fun for everyone to see all the options that get created.

I want to give it some more bake time and internal testing before cutting a release (plus needing to document it, etc).  But if anyone wants a preview, feel free to pull master and give it a shot!  Let me know any feedback in this thread.

**Comment by chrisrude** [comment]
Specifically, it requires the AUTOMATIC1111 UI to be running.

It needs a little more work before I'm happy with it though, specifically it has a hard time on knowing when an image request is being made.  I'm planning to play with some zero-shot classifiers to see if one would help, but using one would add to the install footprint.

**Comment by Skrownerve** [comment]
How does one run the cutting-edge version? I'm trying everything I can think of, but I can't get pip to install anything but 0.1.3 and cloning the project doesn't seem to work either.

**Comment by TruthSearchers** [comment]
Still confused a lil bit of how to do it

**Comment by chrisrude** [comment]
0.1.4 is out!  Should be simpler now to install the latest by using:
```bash
pip install oobabot --upgrade
```
