### ISSUE TITLE
Won't connect to Stable Diffusion

### ISSUE THREAD

**Issue by Casuallynoted** [chrisrude/oobabot#74]
Hello!

I'm trying to get the bot to launch and connect to my (working) stable diffusion web ui instance. I can confirm the API is up and running, but when I use any of these as the option in the config text file, it refuses to boot and tells me the url is wrong. Here is what I've tried:

ws://127.0.0.1:7861
ws://localhost:7861
http://127.0.0.1:7861
http://localhost:7861

Is there anything else I can try to get it running?

**Comment by Mage-Enderman** [comment]
Same issue, would love to know how to connect it!

**Comment by jmoney7823956789378** [comment]
I'm not telepathic enough to know your network setup, but are you running oobabooga + a1111 + oobabot on the same machine, without docker or containerization in between?

**Comment by Mage-Enderman** [comment]
As far as I know yes oobabooga + a1111 + oobabot on the same machine, without docker or containerization in between
oogabooga made the environment env but I don't think it's in a container

**Comment by xydreen** [comment]
> Hello!
> 
> I'm trying to get the bot to launch and connect to my (working) stable diffusion web ui instance. I can confirm the API is up and running, but when I use any of these as the option in the config text file, it refuses to boot and tells me the url is wrong. Here is what I've tried:
> 
> ws://127.0.0.1:7861 ws://localhost:7861 http://127.0.0.1:7861 http://localhost:7861
> 
> Is there anything else I can try to get it running?

Out of that list, http://127.0.0.1:7861 is the correct URL to use in the oobabot configuration file, and assuming that this URL is accessible via the same machine you are running A1111 on.

Show me the launch parameters you use for stable diffusion, please. IE, ./webui.sh --api so forth and so on.

Also, show me the entire console (terminal) log for oobabot, from launch to oobabot exiting prematurely.



> As far as I know yes oobabooga + a1111 + oobabot on the same machine, without docker or containerization in between oogabooga made the environment env but I don't think it's in a container

Do the same as the above.

**Comment by Casuallynoted** [comment]
Whoops, looks like I didn't have the --api flag on SD! That fixed it!
