### ISSUE TITLE
Circular Import issue

### ISSUE THREAD

**Issue by nrchamb** [chrisrude/oobabot#81]
I keep trying to set up the bot, but it doesn't seem to do much for me.

After running pip install, it tells me everything is good to go. When I try to run the script, it gives me this error.

PS F:\uwu-bot\OogaBooga\oobabooga_windows\text-generation-webui\modules\oobabot\src\oobabot> python oobabot.py
Traceback (most recent call last):
  File "F:\uwu-bot\OogaBooga\oobabooga_windows\text-generation-webui\modules\oobabot\src\oobabot\oobabot.py", line 14, in <module>
    import oobabot
  File "F:\uwu-bot\OogaBooga\oobabooga_windows\text-generation-webui\modules\oobabot\src\oobabot\oobabot.py", line 15, in <module>
    from oobabot import discord_utils
ImportError: cannot import name 'discord_utils' from partially initialized module 'oobabot' (most likely due to a circular import) (F:\uwu-bot\OogaBooga\oobabooga_windows\text-generation-webui\modules\oobabot\src\oobabot\oobabot.py)
PS F:\uwu-bot\OogaBooga\oobabooga_windows\text-generation-webui\modules\oobabot\src\oobabot>

I'm new to all of this, so I'm a well of ignorance.

I have oobabooga running. I have the --API flag added. I have the models loaded. I'm not sure if I messed up where I should have the oobabot living, but I'm at a loss. :(

**Comment by jmoney7823956789378** [comment]
You have your oobabot stored way too deep into itself.
Firstly, you should just be abled to traverse to the base of the oobabot root, `pip install .` and then you may call oobabot using `python -m oobabot`

**Comment by nrchamb** [comment]
Fantastic! Thanks for your help. I was looking all over and loosing my mind.

For clarification for anyone else, I moved the folder "oobabot\src\oobabot" from "\oobabot\src\" to the same base folder as Oobabooga - "oobabooga_windows" and the above command worked.
